### ISSUE TITLE
[init/wallet] common.Address design

### ISSUE THREAD

**Issue by RmbRT** [perun-network/go-perun_archived#2]
**Current state**&ensp; Currently, the type `common.Address` is just a generic implementation using a byte array, and utilities for conversion to/from hex strings.

**Problem**&ensp; This may prove insufficient, as not every byte array is necessarily a valid address for a given cryptocurrency, and some cryptocurrencies might display addresses in base58 or similar, which would lead to confusion if perun didn't support that representation.

**Improvement Proposal**&ensp; I propose that we use a more differentiated interface, which allows individual cryptocurrencies to have a better-fitting data model. Additionally, I suggest we provide a default generic implementation, which is similar to the current one, so that lazy developers can use addresses without implementation overhead.
I suggest the `common.Address` interface contains:
* `ToString() string`: Human-readable string (as employed by the cryptocurrency it belongs to, might be hex, base58, …).
* `FromString(string) (*Address, error)`: Parsing of a human-readable representation.
* `FromBytes([]byte) (*Address, error)`: Simple raw deserialisation.
* `ToBytes() []byte`: Simple raw serialisation.

Additionally, it might be of interest to additionally store which domain/blockchain an address belongs to, in order to make debugging and error checking easier.
I suggest the default implementation be named `common.GenericAddress`, and consist of a byte array, and represents addresses as hex strings.

**Comment by MariusVanDerWijden** [comment]
Invalid is not the right label (Invalid is typically used for invalid bug reports)

**Comment by RmbRT** [comment]
Yeah I thought so, too, but all other standard labels seemed fit even less. I didn't want to create duplicate labels, so I chose the best fit.

**Comment by sebastianst** [comment]
We just discussed that
* a `Wallet` interface has a method to return `[]Account`
* an `Account` interface has a `Sign(digest []byte) (signature []byte, error)` and `Addr()` method
* an `Addr` is an address interface, which is
  * a `Stringer`
  * an `Equaler` (interface that implements the `Equals(Equaler) bool` method) :)
  * an `encoding.Binary(Un)Marshaler`

**Comment by MariusVanDerWijden** [comment]
There is no Equaler interface, and I would advise against using a generic equaler interface everywhere. If we use a type specific equal e.g. `Equals(Address) bool` we can only compare addresses with addresses.
I would also propose to add a `FromString(string) Address` function to convert a string to an address. 
Additionally, I would prefer to use `Address` to `Addr` but I am also okay with the latter.

**Comment by RmbRT** [comment]
I agree that `Equals(Address) bool` is a better choice. This prevents comparisons of addresses and different objects. I think that `FromString(string) Address` needs an additional `error` return value. I also agree that `Address` is a cleaner name than `Addr`.

**Comment by sebastianst** [comment]
ACK to `Equal(Address)`, doesn't make sense otherwise.
ACK `FromString(string) Address, error` with error value.
About `Address` vs `Addr`. Yes, it is cleaner, but if we agree now on some common shortcuts, we'll save a lot of characters in the future ;) But if everyone is against `Addr`, let's use `Address`.

Also, let's move discussions to gitlab for the initial development stage in the near future.

**Comment by sebastianst** [comment]
summed it up in gitlab. Let's continue there.
