### ISSUE TITLE
CI-Pipeline

### ISSUE THREAD

**Issue by MariusVanDerWijden** [perun-network/go-perun_archived#3]
Testing & CI/CD is an integral part of our workflow.

**Current state**  We do not have any ci-pipeline.

**Improvement Proposal**  
For setting up a pipeline we need the following things (sorted by importance):

- [x] Repo on the cac gitlab
- [ ] CI-Server on our cluster
- [ ] A name for our cluster (I would propose Entoron)
- [ ] A Makefile for our code
- [ ] A gitlab-yaml file with the configuration
- [ ] A code-coverage tool
- [ ] rules for pushing/merging PRs
- [ ] [GoReport Card](https://goreportcard.com/)

**Comment by sebastianst** [comment]
ACK Entoron!

**Comment by sebastianst** [comment]
And a GoReport card https://goreportcard.com/

**Comment by sebastianst** [comment]
It probably doesn't exist yet: A bot that leaves an in-line comment (in gitlab) on all comment sections above public functions and variables that were changed, if the comment itself was not updated. The idea is that comments rot and changes in the behavior of a function or variable should often lead to the update of the documenting comment section above it. This is particularly important in Go, where the description of a function's behavior via its documentation is sometimes essential.
Definitely a nice procrastination project, if there weren't other things to do :)

**Comment by sebastianst** [comment]
continued in gitlab
