### ISSUE TITLE
[init/db] db.ChanIterator & Co design

### ISSUE THREAD

**Issue by RmbRT** [perun-network/go-perun_archived#4]
**Current State**&ensp; The `db.ChanIterator` is a pair of channels: One for `db.Item` values and one for errors. It is used as a simpler representation of an iterator. `db.IteratorChanWrapper` seems to be a default implementation of the interface. It is created using `db.AsChanIterator(Iterator)`.

**Problem**&ensp; The name is awkward, as `ChanIterator` suggests that the type itself is an iterator (which it is not, it is a pair of channels). It also suggests that it iterates over a list of channels, which it is not, either. Additionally, `IteratorChanWrapper` is inconsistently named with `ChanIterator`. `AsChanIterator` feels awkward.

**Improvement Proposal**&ensp; I suggest that the interface be named more descriptive of what it is, i.e. "Response", "ItemChannel", "Items". I also suggest that `IteratorChanWrapper` be named `Default*` or `*Impl` (where `*` is one of the previous names), as it seems to me that it is simply a default implementation of the interface. `Default*`/`*Impl` seems more descriptive to me than `*Wrapper`, because it actually wraps around the `db.Iterator` type, not around the `IteratorChan` type. I suggest `AsChanIterator` be made a member of the `Iterator` interface, and be renamed to `To*` or `As*` (i.e., `ToItemChannel`, `ToItems`). This coupling makes sense to me, as it is easier to read when used, and I think it is the predominant way in which the `Iterator` interface is read from anyway.

**Comment by sebastianst** [comment]
We discussed to stick only with `Iterator` in the `dev` branch and park the `ChanIterator` in an experimental branch.
