### ISSUE TITLE
[init/make]Makefile issues

### ISSUE THREAD

**Issue by sebastianst** [perun-network/go-perun_archived#5]
There are several issues with the Makefile, probably related to the fact that this is a go module.
## go list
`go list github.com/perun-network/go-perun`, which is called by the Makefile at the beginning, returns
```
can't load package: package github.com/perun-network/go-perun: unknown import path "github.com/perun-network/go-perun": cannot find module providing package github.com/perun-network/go-perun
```

## make dep
AFAIK `go get` is not required any more with modules

## make build
We don't have any binary yet to build. Probably the `test` target, which runs `go test`, is sufficient for the foreseeable future.

**Comment by MariusVanDerWijden** [comment]
Go list currently doesn't work on the branch, because there are no modules there. If you create a go file you can test it.

**Comment by MariusVanDerWijden** [comment]
fixed make dep to export the gomodule flag here: 7b50ce4b67ac2a1b1328a7edc3ca06649a46a44c
I would not remove the build command at this time.

**Comment by sebastianst** [comment]
invalid as we don't use a `Makefile` right now.
